/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NativeWrapper */

#ifndef _Included_com_example_NativeWrapper
#define _Included_com_example_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NativeWrapper
 * Method:    testNativeMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_NativeWrapper_testNativeMethod
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
